/**
 * Aggregator for the AI CMO command center page.
 *
 * Two-phase API:
 *   - `loadCmoFastData()` — DB only (~50-200ms). Drives the page shell.
 *   - `loadCmoSlowData()` — live homepage scrape + PageSpeed + GA4/GSC
 *     (1-15s). Streamed in via React Suspense so the shell renders instantly.
 */
import { Prisma } from "@prisma/client";
import { prisma } from "@/backend/db";
import { fetchPage, type PageSnapshot } from "@/backend/scraper/fetch";
import { fetchPageSpeed, type PageSpeedResult } from "@/backend/pagespeed";
import {
  readCmoSlowCache,
  writeCmoSlowCache,
  type CmoSlowGsc,
  type CmoSlowGa4,
} from "@/backend/cmo-slow-cache";
import {
  loadAhrefsWithCache,
  type CachedAhrefsState,
} from "@/backend/ahrefs-cache";
import {
  listGSCSites,
  listGA4Properties,
  querySearchAnalytics,
  runGA4Report,
} from "@/integrations/google";
import {
  generateCmoLlmAnalysis,
  parseCmoLlmSnapshot,
  toStoredSnapshot,
  type CmoLlmAnalysis,
} from "@/backend/pipelines/cmo-llm-analysis.pipeline";
import { strategyPipeline } from "@/backend/pipelines/strategy.pipeline";
import { extractSocialHandles } from "@/backend/social-extractor";
import { pickAvailableModel } from "@/backend/llm";

export type { CmoLlmAnalysis };

const CMO_LLM_CACHE_MS = 24 * 60 * 60 * 1000;

/**
 * Re-exported tag retained for backward compat — `refreshCmoSlowDataAction`
 * still calls `revalidateTag(CMO_SLOW_TAG)` to drop any stray Next.js
 * route cache entries from before we moved to the DB-backed cache.
 */
export const CMO_SLOW_TAG = "cmo-slow";

export type CmoVoiceProfile = {
  positioning?: string;
  valueProps?: string[];
  competitors?: string[];
  /**
   * Short "how they compete" note per competitor, keyed loosely to the
   * competitors array. Rendered next to the brand favicon in the
   * Competitor analysis drawer.
   */
  competitorNotes?: Array<{ name: string; domain?: string; note: string }>;
  topicClusters?: Array<{ theme: string; keywords: string[] }>;
  channels?: string[];
  siteTitle?: string;
  siteDescription?: string;
  brandVoice?: { tone?: string; style?: string; avoid?: string[] };
  /**
   * Full, CMO-grade Markdown documents shown in the Company panel's
   * side drawer (with copy / PDF / Word / HTML export). Generated by the
   * strategy LLM; when absent the UI composes a fallback from the
   * structured fields above.
   */
  brandVoiceDoc?: string;
  marketingStrategyDoc?: string;
  /** Spread from onboarding strategy.voice */
  tone?: string;
  styleGuidelines?: string[];
  avoid?: string[];
  /**
   * Public social-media handles for the brand. Auto-detected from the
   * website (Claude + regex pre-scan) or manually edited in /settings.
   */
  socialHandles?: {
    twitter?: string;
    instagram?: string;
    linkedin?: string;
    facebook?: string;
    youtube?: string;
    github?: string;
    tiktok?: string;
  };
};

export type SeoIssue = {
  severity: "low" | "medium" | "high";
  category: string;
  title: string;
  fix: string;
  url?: string;
};

export type ActionLite = {
  id: string;
  title: string;
  summary: string | null;
  agent: string;
  priority: string;
  cta: string | null;
  href: string | null;
  createdAt: Date;
};

export type RunLite = {
  id: string;
  agent: string;
  status: string;
  startedAt: Date;
};

export type GscRow = {
  query: string;
  clicks: number;
  impressions: number;
  ctr: number;
  position: number;
};

export type Ga4Row = {
  page: string;
  sessions: number;
  users: number;
  conversions: number;
};

/** Data we can have ready in <200ms from the DB only. */
export type CmoFastData = {
  workspace: {
    id: string;
    name: string;
    websiteUrl: string | null;
    industry: string | null;
    icp: string | null;
    ahrefsSnapshot: unknown;
    ahrefsSnapshotAt: Date | null;
  };
  plan: "FREE" | "MAX";
  credits: number | null;
  voice: CmoVoiceProfile | null;
  integrations: {
    ga4: boolean;
    gsc: boolean;
    reddit: boolean;
    twitter: boolean;
    linkedin: boolean;
    github: boolean;
  };
  scores: {
    seo: number | null;
    geo: number | null;
  };
  topIssues: SeoIssue[];
  topKeywords: Array<{ query: string; intent: string | null }>;
  topCompetitors: string[];
  openActions: ActionLite[];
  recentRuns: RunLite[];
};

/** Data that requires live network calls. Streamed in via Suspense. */
export type CmoSlowData = {
  liveSnapshot: PageSnapshot | null;
  pageSpeed: PageSpeedResult | null;
  gsc: { connected: boolean; rows: GscRow[]; site: string | null };
  ga4: { connected: boolean; rows: Ga4Row[]; property: string | null };
  /** Ahrefs snapshot (DR, backlinks, traffic, top keywords/countries/pages) — cached 24h on Workspace. */
  ahrefs: CachedAhrefsState;
  /** Homepage-only LLM analysis (one provider key). Cached on Workspace.cmoLlmSnapshot. */
  llmAnalysis: CmoLlmAnalysis | null;
  /**
   * If voiceProfile was empty when the page started loading (e.g. right after
   * the user changed their site URL), we lazily regenerate the strategy here
   * so the Company panel populates competitors / positioning / channels on
   * the same page render instead of forcing the user to re-run an agent.
   */
  freshVoice: CmoVoiceProfile | null;
  freshIndustry: string | null;
  freshIcp: string | null;
  /**
   * If no SEO audit / GEO snapshot existed when the dashboard loaded, we
   * lazily auto-run those agents once and surface the fresh results here so
   * the Analytics panel populates without the user manually opening each
   * agent. Null when an audit/snapshot already existed (read from fast data)
   * or the auto-run was skipped/failed.
   */
  freshSeoScore: number | null;
  freshSeoIssues: SeoIssue[] | null;
  freshGeoScore: number | null;
  /**
   * Crawler / AI accessibility files probed directly over HTTP — drives the
   * GEO tab's "Site Files" section (robots.txt, llms.txt, sitemap.xml).
   */
  siteFiles: SiteFileCheck[];
  /**
   * Latest cached AI_VISIBILITY result (Apify) summarised for the GEO tab's
   * "AI citations" breakdown. Null when the GEO agent's AI-visibility run
   * hasn't been cached yet.
   */
  aiCitations: AiCitationsSummary | null;
};

export type SiteFileCheck = {
  name: string;
  path: string;
  present: boolean;
  sizeBytes: number | null;
};

export type AiCitationsSummary = {
  domain: string;
  fetchedAt: string;
  total: number;
  platforms: Array<{
    key: string;
    label: string;
    citations: number;
    delta: number | null;
  }>;
};

const AI_PLATFORM_LABEL: Record<string, string> = {
  aiOverviews: "AI Overviews",
  chatgpt: "ChatGPT",
  gemini: "Gemini",
  perplexity: "Perplexity",
  copilot: "Copilot",
  grok: "Grok",
};

/** Read the latest cached AI_VISIBILITY run and summarise it for the GEO tab. */
async function loadAiCitationsSummary(
  workspaceId: string,
  websiteUrl: string
): Promise<AiCitationsSummary | null> {
  let domain = "";
  try {
    const u = websiteUrl.startsWith("http") ? websiteUrl : `https://${websiteUrl}`;
    domain = new URL(u).hostname.replace(/^www\./, "");
  } catch {
    domain = websiteUrl;
  }
  let row;
  try {
    row = await prisma.seoToolRun.findFirst({
      where: { workspaceId, tool: "AI_VISIBILITY" },
      orderBy: { createdAt: "desc" },
    });
  } catch {
    return null;
  }
  if (!row) return null;
  const result = row.result as {
    byProvider?: Array<{
      platform?: string;
      citations?: number | null;
      priorMonthCitations?: number | null;
    }>;
  };
  const byProvider = Array.isArray(result?.byProvider) ? result.byProvider : [];
  const platforms = byProvider
    .filter((r) => r.platform && AI_PLATFORM_LABEL[r.platform])
    .map((r) => {
      const citations = r.citations ?? 0;
      const prior = r.priorMonthCitations;
      return {
        key: r.platform as string,
        label: AI_PLATFORM_LABEL[r.platform as string],
        citations,
        delta: typeof prior === "number" ? citations - prior : null,
      };
    });
  if (platforms.length === 0) return null;
  const total = platforms.reduce((acc, p) => acc + p.citations, 0);
  return { domain, fetchedAt: row.createdAt.toISOString(), total, platforms };
}

/** Combined view (used after both phases resolve). */
export type CmoData = CmoFastData & CmoSlowData;

export async function loadCmoFastData(args: {
  workspaceId: string;
  websiteUrl: string | null;
  workspaceName: string;
  industry: string | null;
  icp: string | null;
  voiceProfile: unknown;
  plan: "FREE" | "MAX";
  credits: number | null;
  ahrefsSnapshot?: unknown;
  ahrefsSnapshotAt?: Date | null;
}): Promise<CmoFastData> {
  const voice = (args.voiceProfile ?? null) as CmoVoiceProfile | null;

  // Auto-resolve stale onboarding actions whose precondition is now satisfied.
  // Most common case: "Add a working LLM API key" gets seeded during onboarding
  // when no provider was configured; the action sits forever even after the
  // user wires Anthropic/OpenAI/etc. Mark it DONE so the actions feed
  // doesn't keep nagging.
  if (pickAvailableModel() != null) {
    try {
      await prisma.actionItem.updateMany({
        where: {
          workspaceId: args.workspaceId,
          status: "OPEN",
          title: "Add a working LLM API key",
        },
        data: { status: "DONE" },
      });
    } catch {
      // non-fatal — better to render the dashboard than fail it for cleanup.
    }
  }

  const [
    integrations,
    latestAudit,
    latestGeo,
    keywords,
    openActions,
    recentRuns,
  ] = await Promise.all([
    prisma.integration.findMany({
      where: { workspaceId: args.workspaceId },
      select: { provider: true },
    }),
    prisma.siteAudit.findFirst({
      where: { workspaceId: args.workspaceId },
      orderBy: { ranAt: "desc" },
    }),
    prisma.geoScoreSnapshot.findFirst({
      where: { workspaceId: args.workspaceId },
      orderBy: { date: "desc" },
    }),
    prisma.keyword.findMany({
      where: { workspaceId: args.workspaceId },
      orderBy: { trackedSince: "desc" },
      take: 8,
      select: { query: true, intent: true },
    }),
    prisma.actionItem.findMany({
      where: { workspaceId: args.workspaceId, status: "OPEN" },
      orderBy: [{ priority: "desc" }, { createdAt: "desc" }],
      take: 60,
    }),
    prisma.agentRun.findMany({
      where: { workspaceId: args.workspaceId },
      orderBy: { startedAt: "desc" },
      take: 12,
      select: { id: true, agent: true, status: true, startedAt: true },
    }),
  ]);

  const integrationSet = new Set(integrations.map((i) => i.provider));
  const topIssues: SeoIssue[] = Array.isArray(latestAudit?.issues)
    ? (latestAudit.issues as unknown[])
        .filter((x): x is SeoIssue => isIssue(x))
        .slice(0, 12)
    : [];

  const topCompetitors = Array.isArray(voice?.competitors)
    ? voice.competitors.slice(0, 12)
    : [];

  return {
    workspace: {
      id: args.workspaceId,
      name: args.workspaceName,
      websiteUrl: args.websiteUrl,
      industry: args.industry,
      icp: args.icp,
      ahrefsSnapshot: args.ahrefsSnapshot ?? null,
      ahrefsSnapshotAt: args.ahrefsSnapshotAt ?? null,
    },
    plan: args.plan,
    credits: args.credits,
    voice,
    integrations: {
      ga4: integrationSet.has("GOOGLE_ANALYTICS"),
      gsc: integrationSet.has("GOOGLE_SEARCH_CONSOLE"),
      reddit: integrationSet.has("REDDIT"),
      twitter: integrationSet.has("TWITTER"),
      linkedin: integrationSet.has("LINKEDIN"),
      github: integrationSet.has("GITHUB"),
    },
    scores: {
      seo: latestAudit?.score ?? null,
      geo: latestGeo?.score ?? null,
    },
    topIssues,
    topKeywords: keywords,
    topCompetitors,
    openActions: openActions.map((a) => ({
      id: a.id,
      title: a.title,
      summary: a.summary,
      agent: a.agent,
      priority: a.priority,
      cta: a.cta,
      href: a.href,
      createdAt: a.createdAt,
    })),
    recentRuns,
  };
}

export async function loadCmoSlowData(args: {
  workspaceId: string;
  websiteUrl: string | null;
  industry: string | null;
  icp: string | null;
  voice?: CmoVoiceProfile | null;
  ga4Connected: boolean;
  gscConnected: boolean;
  withPageSpeed?: boolean;
  ahrefsSnapshot?: unknown;
  ahrefsSnapshotAt?: Date | null;
}): Promise<CmoSlowData> {
  const {
    websiteUrl,
    industry,
    icp,
    voice,
    ga4Connected,
    gscConnected,
    withPageSpeed = true,
  } = args;

  // ---- DB-backed snapshot lookup ----
  // The snapshot is the SINGLE source of truth for "this URL has been
  // fully processed". A fresh snapshot means we already ran homepage
  // scrape + PageSpeed + GA4 + GSC + the lazy strategy regen + social
  // handle detection. Hitting it = ~50ms total instead of 30-60s.
  const cached = await readCmoSlowCache({
    workspaceId: args.workspaceId,
    websiteUrl,
  });

  let liveSnapshot: PageSnapshot | null;
  let pageSpeed: PageSpeedResult | null;
  let gscData: CmoSlowGsc | null;
  let ga4Data: CmoSlowGa4 | null;
  const ahrefs = await loadAhrefsWithCache({
    workspaceId: args.workspaceId,
    websiteUrl,
    ahrefsSnapshot: args.ahrefsSnapshot,
    ahrefsSnapshotAt: args.ahrefsSnapshotAt ?? null,
  });

  if (cached) {
    console.info(
      `[cmo-cache] hit · workspace=${args.workspaceId} url=${websiteUrl}`
    );
    liveSnapshot = cached.liveSnapshot;
    pageSpeed = cached.pageSpeed;
    // Honour current integration state — if the user disconnected GA4/GSC
    // since the snapshot was taken, don't show stale rows.
    gscData = gscConnected ? cached.gsc : null;
    ga4Data = ga4Connected ? cached.ga4 : null;
  } else {
    console.info(
      `[cmo-cache] miss · workspace=${args.workspaceId} url=${websiteUrl} — fetching fresh slow bundle`
    );
    [liveSnapshot, pageSpeed, gscData, ga4Data] = await Promise.all([
      websiteUrl ? fetchPage(websiteUrl).catch(() => null) : Promise.resolve(null),
      withPageSpeed && websiteUrl
        ? fetchPageSpeed(websiteUrl).catch(() => null)
        : Promise.resolve(null),
      gscConnected ? loadGsc(args.workspaceId) : Promise.resolve(null),
      ga4Connected ? loadGa4(args.workspaceId) : Promise.resolve(null),
    ]);

    // AWAIT the write — previously fire-and-forget, which could race with
    // a fast follow-up navigation. ~50ms cost on the cold path (already 30s)
    // in exchange for guaranteed persistence on every cache miss.
    if (websiteUrl) {
      await writeCmoSlowCache({
        workspaceId: args.workspaceId,
        websiteUrl,
        data: { liveSnapshot, pageSpeed, gsc: gscData, ga4: ga4Data },
      });
      console.info(
        `[cmo-cache] persisted · workspace=${args.workspaceId} url=${websiteUrl}`
      );
    }
  }

  let llmAnalysis: CmoLlmAnalysis | null = null;
  try {
    llmAnalysis = await resolveCmoLlmAnalysis({
      workspaceId: args.workspaceId,
      websiteUrl,
      industry,
      icp,
      liveSnapshot,
    });
  } catch (err) {
    console.error("[cmo] resolveCmoLlmAnalysis failed:", err);
  }

  // Lazy strategy refresh — runs when the workspace has a URL but no voice
  // profile yet (e.g. user just changed the site in Settings, which clears
  // voice + cached snapshot). Failures are non-fatal: we just leave voice
  // unset and the user can re-run agents manually.
  //
  // CRITICAL: skip when the slow snapshot is fresh. A fresh snapshot proves
  // we already ran strategy regen for this URL inside the previous render —
  // if voice still appears empty afterwards, the LLM call either failed or
  // returned a thin result; re-running won't help and just burns 10-30s of
  // Claude credits on every page visit.
  let freshVoice: CmoVoiceProfile | null = null;
  let freshIndustry: string | null = null;
  let freshIcp: string | null = null;
  if (!cached && websiteUrl && isVoiceEmpty(voice ?? null)) {
    try {
      const { strategy, snapshot } = await strategyPipeline.generate({
        workspaceId: args.workspaceId,
        websiteUrl,
      });
      freshVoice = {
        ...strategy.voice,
        positioning: strategy.positioning,
        valueProps: strategy.valueProps,
        competitors: strategy.competitors,
        competitorNotes: strategy.competitorNotes,
        topicClusters: strategy.topicClusters,
        channels: strategy.channels,
        siteTitle: snapshot.title,
        siteDescription: snapshot.description,
      };
      freshIndustry = strategy.industry;
      freshIcp = strategy.icp;

      try {
        await prisma.workspace.update({
          where: { id: args.workspaceId },
          data: {
            industry: freshIndustry,
            icp: freshIcp,
            voiceProfile: JSON.parse(
              JSON.stringify(freshVoice)
            ) as Prisma.InputJsonValue,
          },
        });
      } catch (err) {
        console.error("[cmo] failed to persist regenerated strategy:", err);
      }
    } catch (err) {
      console.error("[cmo] lazy strategy regen failed:", err);
    }
  }

  // Auto-detect social handles when websiteUrl is set and we haven't found them
  // yet OR the cached handles look stale for the current site (e.g. user just
  // switched the workspace to a different domain — old handles must not linger).
  const currentVoice = freshVoice ?? voice ?? null;
  const handleValues = Object.values(currentVoice?.socialHandles ?? {}).filter(
    (v): v is string => typeof v === "string" && v.trim().length > 0
  );
  const hasHandles = handleValues.length > 0;
  const currentHost = ((): string | null => {
    if (!websiteUrl) return null;
    try {
      const u = websiteUrl.startsWith("http") ? websiteUrl : `https://${websiteUrl}`;
      return new URL(u).hostname.replace(/^www\./, "").toLowerCase();
    } catch {
      return null;
    }
  })();
  const brandRoot = currentHost ? currentHost.split(".")[0] : null;
  // Heuristic: if the brand slug (e.g. "anthropic" from anthropic.com) does
  // NOT appear in any cached handle, the handles probably belong to a
  // previous workspace site and should be refreshed.
  const handlesLookStale =
    hasHandles &&
    !!brandRoot &&
    !handleValues.some((v) => v.toLowerCase().includes(brandRoot));
  // Same cache-aware guard as strategy regen — fresh snapshot means handle
  // detection already ran for this URL during the previous cold load, so
  // skip it to keep tab-switching free.
  const shouldRunHandleDetect =
    !cached && websiteUrl && (!hasHandles || handlesLookStale);
  // When we're about to refresh stale handles, drop the old ones so the in-memory
  // voice doesn't keep rendering the previous site's pills during this request.
  if (handlesLookStale && currentVoice) {
    currentVoice.socialHandles = undefined;
  }
  if (shouldRunHandleDetect) {
    try {
      const detected = await extractSocialHandles(websiteUrl);
      if (Object.keys(detected.handles).length > 0) {
        const mergedVoice: CmoVoiceProfile = {
          ...(currentVoice ?? {}),
          socialHandles: {
            ...(currentVoice?.socialHandles ?? {}),
            ...detected.handles,
          },
        };
        try {
          await prisma.workspace.update({
            where: { id: args.workspaceId },
            data: {
              voiceProfile: JSON.parse(
                JSON.stringify(mergedVoice)
              ) as Prisma.InputJsonValue,
            },
          });
        } catch (err) {
          console.error("[cmo] failed to persist auto-detected social handles:", err);
        }
        if (freshVoice) {
          freshVoice = mergedVoice;
        } else {
          // Reflect into the in-memory voice variable so this render shows them.
          if (voice) {
            voice.socialHandles = mergedVoice.socialHandles;
          } else {
            freshVoice = mergedVoice;
          }
        }
      }
    } catch (err) {
      console.error("[cmo] social-handle auto-detect failed:", err);
    }
  }

  // Lazy auto-run of SEO + GEO so the Analytics panel populates without the
  // user manually opening each agent. Strictly gated: only fires when there
  // is NO existing audit / GEO snapshot (i.e. a brand-new site), and the
  // result row that the agent writes prevents it from re-running on the next
  // load. Both run in parallel and are fully best-effort.
  let freshSeoScore: number | null = null;
  let freshSeoIssues: SeoIssue[] | null = null;
  let freshGeoScore: number | null = null;
  if (websiteUrl && pickAvailableModel() != null) {
    // Dedupe: if an agent ran (or is running) in the last 10 minutes, don't
    // kick a duplicate — this stops a refresh during the first audit from
    // double-billing while the first run is still in flight.
    const tenMinAgo = new Date(Date.now() - 10 * 60 * 1000);
    const [existingAudit, existingGeo, recentSeoRun, recentGeoRun] =
      await Promise.all([
        prisma.siteAudit
          .findFirst({
            where: { workspaceId: args.workspaceId },
            orderBy: { ranAt: "desc" },
            select: { score: true, issues: true },
          })
          .catch(() => null),
        prisma.geoScoreSnapshot
          .findFirst({ where: { workspaceId: args.workspaceId } })
          .catch(() => null),
        prisma.agentRun
          .findFirst({
            where: {
              workspaceId: args.workspaceId,
              agent: "seo",
              startedAt: { gte: tenMinAgo },
            },
          })
          .catch(() => null),
        prisma.agentRun
          .findFirst({
            where: {
              workspaceId: args.workspaceId,
              agent: "geo",
              startedAt: { gte: tenMinAgo },
            },
          })
          .catch(() => null),
      ]);

    // An audit that scored the site but carries no usable issues is
    // degenerate (e.g. the LLM returned an empty list before the rule-based
    // backfill landed, or a thin/bot-blocked scrape). Treat a low-scoring,
    // issue-less audit as "needs a real run" so the Checks tab self-heals.
    // The 10-minute `recentSeoRun` dedupe below still prevents loop-billing,
    // and a genuinely clean site (score ≥ 90) is left alone.
    const auditHasUsableIssues =
      !!existingAudit &&
      Array.isArray(existingAudit.issues) &&
      (existingAudit.issues as unknown[]).some((x) => isIssue(x));
    const auditIsDegenerate =
      !!existingAudit &&
      !auditHasUsableIssues &&
      (existingAudit.score ?? 0) < 90;

    const tasks: Array<Promise<void>> = [];
    if ((!existingAudit || auditIsDegenerate) && !recentSeoRun) {
      tasks.push(
        (async () => {
          try {
            const { seoAgent } = await import("@/backend/agents/seo");
            const { executeAgent } = await import("@/backend/agents/base");
            const res = await executeAgent(seoAgent, args.workspaceId, {});
            if (res.ok && res.output) {
              const out = res.output as { score?: number; issues?: unknown[] };
              freshSeoScore = typeof out.score === "number" ? out.score : null;
              freshSeoIssues = Array.isArray(out.issues)
                ? (out.issues as unknown[]).filter((x): x is SeoIssue => isIssue(x))
                : null;
            }
          } catch (err) {
            console.error("[cmo] lazy SEO auto-run failed:", err);
          }
        })()
      );
    }
    if (!existingGeo && !recentGeoRun) {
      tasks.push(
        (async () => {
          try {
            const { geoAgent } = await import("@/backend/agents/geo");
            const { executeAgent } = await import("@/backend/agents/base");
            const res = await executeAgent(geoAgent, args.workspaceId, {});
            if (res.ok && res.output) {
              const out = res.output as { score?: number };
              freshGeoScore = typeof out.score === "number" ? out.score : null;
            }
          } catch (err) {
            console.error("[cmo] lazy GEO auto-run failed:", err);
          }
        })()
      );
    }
    if (tasks.length) await Promise.all(tasks);
  }

  // Probe crawler / AI-accessibility files + read cached AI citations for
  // the GEO tab, in parallel.
  const [siteFiles, aiCitations] = await Promise.all([
    websiteUrl ? probeSiteFiles(websiteUrl) : Promise.resolve([]),
    websiteUrl
      ? loadAiCitationsSummary(args.workspaceId, websiteUrl)
      : Promise.resolve(null),
  ]);

  return {
    liveSnapshot,
    pageSpeed,
    gsc: gscData ?? { connected: gscConnected, rows: [], site: null },
    ga4: ga4Data ?? { connected: ga4Connected, rows: [], property: null },
    ahrefs,
    llmAnalysis,
    freshVoice,
    freshIndustry,
    freshIcp,
    freshSeoScore,
    freshSeoIssues,
    freshGeoScore,
    siteFiles,
    aiCitations,
  };
}

/**
 * HEAD/GET the three files LLM crawlers look for. Bounded to 5s each and
 * fully best-effort — a failed probe just reports the file as missing.
 */
async function probeSiteFiles(websiteUrl: string): Promise<SiteFileCheck[]> {
  let origin: string;
  try {
    const u = websiteUrl.startsWith("http") ? websiteUrl : `https://${websiteUrl}`;
    origin = new URL(u).origin;
  } catch {
    return [];
  }
  const targets: Array<{ name: string; path: string }> = [
    { name: "robots.txt", path: "/robots.txt" },
    { name: "llms.txt", path: "/llms.txt" },
    { name: "sitemap.xml", path: "/sitemap.xml" },
  ];
  return Promise.all(
    targets.map(async ({ name, path }) => {
      try {
        const ctrl = new AbortController();
        const t = setTimeout(() => ctrl.abort(), 5000);
        const res = await fetch(`${origin}${path}`, {
          method: "GET",
          redirect: "follow",
          signal: ctrl.signal,
          headers: { "user-agent": "XicmoBot/1.0 (+geo-audit)" },
        });
        clearTimeout(t);
        if (!res.ok) {
          return { name, path, present: false, sizeBytes: null };
        }
        const body = await res.text();
        // Some hosts return a 200 HTML page for missing files — guard against
        // that for robots/llms by requiring it not to look like a full doc.
        const looksLikeHtml = /<html[\s>]/i.test(body.slice(0, 200));
        const present = name === "sitemap.xml" ? true : !looksLikeHtml;
        return {
          name,
          path,
          present,
          sizeBytes: present ? new TextEncoder().encode(body).length : null,
        };
      } catch {
        return { name, path, present: false, sizeBytes: null };
      }
    })
  );
}

function isVoiceEmpty(voice: CmoVoiceProfile | null): boolean {
  if (!voice) return true;
  const hasCompetitors = Array.isArray(voice.competitors) && voice.competitors.length > 0;
  const hasValueProps = Array.isArray(voice.valueProps) && voice.valueProps.length > 0;
  const hasPositioning = !!(voice.positioning && voice.positioning.trim().length > 0);
  return !hasCompetitors && !hasValueProps && !hasPositioning;
}

async function resolveCmoLlmAnalysis(args: {
  workspaceId: string;
  websiteUrl: string | null;
  industry: string | null;
  icp: string | null;
  liveSnapshot: PageSnapshot | null;
}): Promise<CmoLlmAnalysis | null> {
  const { workspaceId, websiteUrl, industry, icp, liveSnapshot } = args;
  if (!websiteUrl || !liveSnapshot || liveSnapshot.status >= 400) {
    return null;
  }

  const row = await prisma.workspace.findUnique({
    where: { id: workspaceId },
    select: { cmoLlmSnapshot: true },
  });

  const cached = parseCmoLlmSnapshot(
    row?.cmoLlmSnapshot,
    websiteUrl,
    CMO_LLM_CACHE_MS
  );
  if (cached) return cached;

  const fresh = await generateCmoLlmAnalysis({
    workspaceId,
    websiteUrl,
    industry,
    icp,
    snapshot: liveSnapshot,
  });
  if (!fresh) return null;

  try {
    await prisma.workspace.update({
      where: { id: workspaceId },
      data: {
        cmoLlmSnapshot: toStoredSnapshot(websiteUrl, fresh) as Prisma.InputJsonValue,
      },
    });
  } catch (err) {
    console.error("[cmo] cache cmoLlmSnapshot failed (migrate DB?):", err);
  }

  return fresh;
}

/** Backwards-compatible single-shot loader (fast + slow). */
export async function loadCmoData(args: {
  workspaceId: string;
  websiteUrl: string | null;
  workspaceName: string;
  industry: string | null;
  icp: string | null;
  voiceProfile: unknown;
  plan: "FREE" | "MAX";
  credits: number | null;
  withPageSpeed?: boolean;
}): Promise<CmoData> {
  const fast = await loadCmoFastData(args);
  const slow = await loadCmoSlowData({
    workspaceId: args.workspaceId,
    websiteUrl: args.websiteUrl,
    industry: args.industry,
    icp: args.icp,
    voice: fast.voice,
    ga4Connected: fast.integrations.ga4,
    gscConnected: fast.integrations.gsc,
    withPageSpeed: args.withPageSpeed,
  });
  return { ...fast, ...slow };
}

async function loadGsc(
  workspaceId: string
): Promise<CmoSlowData["gsc"]> {
  try {
    const sites = await listGSCSites(workspaceId);
    if (sites.length === 0) return { connected: true, rows: [], site: null };
    const site = sites[0];
    const rows = await querySearchAnalytics(workspaceId, site.siteUrl, {
      dimensions: ["query"],
      rowLimit: 25,
    });
    return {
      connected: true,
      site: site.siteUrl,
      rows: rows.map((r) => ({
        query: r.keys[0] ?? "",
        clicks: r.clicks,
        impressions: r.impressions,
        ctr: r.ctr,
        position: r.position,
      })),
    };
  } catch {
    return { connected: true, rows: [], site: null };
  }
}

async function loadGa4(
  workspaceId: string
): Promise<CmoSlowData["ga4"]> {
  try {
    const props = await listGA4Properties(workspaceId);
    if (props.length === 0)
      return { connected: true, rows: [], property: null };
    const prop = props[0];
    const rows = await runGA4Report(workspaceId, prop.name, {
      dimensions: ["pagePath"],
      metrics: ["sessions", "activeUsers", "conversions"],
      limit: 15,
    });
    return {
      connected: true,
      property: prop.displayName,
      rows: rows.map((r) => ({
        page: r.dimensions[0] ?? "/",
        sessions: r.metrics[0] ?? 0,
        users: r.metrics[1] ?? 0,
        conversions: r.metrics[2] ?? 0,
      })),
    };
  } catch {
    return { connected: true, rows: [], property: null };
  }
}

function isIssue(x: unknown): x is SeoIssue {
  if (!x || typeof x !== "object") return false;
  const o = x as Record<string, unknown>;
  return (
    typeof o.title === "string" &&
    typeof o.fix === "string" &&
    typeof o.category === "string" &&
    (o.severity === "low" || o.severity === "medium" || o.severity === "high")
  );
}
